version: 2.1

jobs:
  test:
      steps:
        - checkout
        - restore_cache:
            key: circleci-java-maven-{{ checksum "pom.xml" }}
        - run:
            command: mvn clean install
        - save_cache:
            paths:
              - ~/.m2
            key: circleci-java-maven-{{ checksum "pom.xml" }}
        - persist_to_workspace:
            root: '.'
            paths:
              - target
        - run:
            name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always
        - store_test_results:
            path: ~/test-results
        - store_artifacts:
            path: ~/test-results/junit

  deploy:
      machine: 
        image: default
      working_directory: ~/
      steps:
        - attach_workspace:
            at: '.'
        - run:
            name: "preparing"
            command: |
              yum list installed
              

workflows:
  test-deploy:
    jobs:
      - deploy
#      - test
#      - deploy:
#            requires:
#                - test
#           filters:
#               branches:
#                 only: master
