version: 2.1

jobs:
  test:
      machine: 
        image: default
      steps:
        - checkout
        - restore_cache:
            key: circleci-java-maven-{{ checksum "pom.xml" }}
        - run:
            command: mvn clean install
        - save_cache:
            paths:
              - ~/.m2
            key: circleci-java-maven-{{ checksum "pom.xml" }}
        - persist_to_workspace:
            root: '.'
            paths:
              - target
        - run:
            name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always
        - store_test_results:
            path: ~/test-results
        - store_artifacts:
            path: ~/test-results/junit

  deploy:
      machine: 
        image: default
      steps:
        - checkout
        - run:
            name: "preparing"
            command: |
               tar -zxvf /home/circleci/project/ibmcloud/IBM_Cloud_CLI_2.1.1_amd64.tar.gz
               ls -ltr /home/circleci/project/ibmcloud
               /home/circleci/project/ibmcloud/Bluemix_CLI/install
               ibmcloud dev help
#               curl -k https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
#               sudo apt-get update 
#               sudo apt-get install -y curl
#               curl -V              
#               tar -zxvf /home/circleci/ibmcloud/IBM_Cloud_CLI_2.1.1_amd64.tar.gz
#              sudo apt-get update
              

workflows:
  test-deploy:
    jobs:
      - deploy
#      - test
#      - deploy:
#            requires:
#                - test
#           filters:
#               branches:
#                 only: master
