drop table userinfo;

create table userinfo(
  id integer generated by default as identity, 
  username varchar(50) not null, 
  password varchar(256) not null, 
  create_time timestamp not null DEFAULT CURRENT_TIMESTAMP, 
  modified_time timestamp not null DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE(username)
);