drop table userinfo;

create table userinfo(
  id integer generated by default as identity, 
  username varchar(50) not null, 
  password varchar(256) not null, 
  create_time timestamp DEFAULT CURRENT_TIMESTAMP, 
  modified_time timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE(username)
);


--sampledata
INSERT INTO userinfo (USERNAME, PASSWORD) values ('user1', 'zaq12wsx');
